language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "tea-commerce-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: tea-commerce # see README
  api_key:
    secure: "v3ajCmpGjCpOQPvKZOYjCpbbLLOKxUbNKQJ9/CZGbMes+j+JnvJUb2rNwck+hjWN0ZmjC+WEButNYgCdip2PC7xgeXWvvOLuZMZBTkJYNwVFPWnbBrpL6fbFp9Sc/y0PIw5ez1iBVAB5bxuolKX0WPpE+P2JbNYu2RnZLlp+3v50wkaddjHNZcKtbF78uYzi19EwWsR2SBgeDTEyMxTDWKszsyKRHeroPovi49gRw2CKEAr/cthWNTdZzB7+S5FX6iTiMdnLUslIrCx4yOPVST1FO89Tbcmn4KYw5fwjL+kXpaequLVdFROEZZaDy0bUXYjNYOQ1ft/kAjedjgaoTWKKZMT1MzV6vIYx2byAU+72pSTgINsqdu3lfzdhtNd1yWmEMO34zbgTtaaNM6DB7dnRClNIT6hCGj7XpjLNU3WImj06PWObG+eFKkHt/4JeSqZMooB/wRAZL1lYIRVGT0aBPY1fibiHkgRA4al0c9N8Cn+8wTbB545AicKMnFPD5sJOsW63XODUR9ae4/aBe4lCnFtwSL4ETH1CZOOvUPWTDvzfjiHAbW60TmsoYdPArY1kNb/JfR5WDRPVGTHnrDeD/q0rd2rb1LNez8AhfwIx2UOGmQGeU43n1shGKiwSBG5KJhyKtPk9lYdQJe/nUJkJb4bZ2N1tAbr7mbjsbKE=" # see README
